---
Ttree:
  ContentRepositoryImporter:

    sources:
      default:
        driver: 'pdo_mysql'
        dbname: ''
        host: '127.0.0.1'
        user: ''
        password: ''

    dataTypeOptions:
      'Ttree\ContentRepositoryImporter\DataType\ExternalResource':
        downloadDirectory: '%FLOW_PATH_DATA%Persistent/Ttree.ContentRepositoryImporter/Downloads/'

      'Ttree\ContentRepositoryImporter\DataType\HtmlContent':
        htmlPurifierOptions:
          'HTML.AllowedElements': 'a,em,i,strong,b,blockquote,p,ul,ol,li'
          'HTML.AllowedAttributes': 'a.href,a.title'
          'HTML.TidyLevel': 'light'
        preProcessing:
          '#\[b\](.+)\[/b\]#i': '<strong>$1</strong>'
          '#\[i\](.+)\[/i\]#i': '<em>$1</em>'
        processingPerLine:
          '#^<b>(.+)</b>$#': '<h3>$1</h3>'
        postProcessing:
          '#^(?!.*?(?:<.*ul>|<.*li>|<.*ol>|<.*h.*>))(.+)$#uim': '<p>$1</p>'

#    presets:
#      'base':
#        'news':
#          label: 'News Import'
#          dataProviderClassName: 'Your\Package\Importer\DataProvider\NewsDataProvider'
#          importerClassName: 'Your\Package\Importer\Importer\NewsImporter'
#
#        'page':
#          label: 'Page Import'
#          dataProviderClassName: 'Your\Package\Importer\DataProvider\PageDataProvider'
#          importerClassName: 'Your\Package\Importer\Importer\PageImporter'
#          batchSize': 120
#
#        'pageContent':
#          label: 'Page Content Import'
#          dataProviderClassName: 'Your\Package\Importer\DataProvider\PageContentDataProvider'
#          importerClassName: 'Your\Package\Importer\Importer\PageContentImporter'
#          batchSize: 120